# Generated by Django 4.1.1 on 2022-10-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_constacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constacto',
            new_name='Contacto',
        ),
    ]
